# Generated by Django 4.1.7 on 2023-03-29 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vehicle_model', models.CharField(max_length=50)),
                ('Vehicle_number', models.CharField(max_length=15, unique=True)),
                ('seating_capacity', models.IntegerField(default=5)),
                ('rent_per_day', models.IntegerField()),
                ('is_booked', models.BooleanField(default=False)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_Bookings_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vehicle_data.vehicle')),
            ],
            options={
                'verbose_name': "Vehicle's Bookings Log",
                'verbose_name_plural': "Vehicle's Bookings Logs",
            },
        ),
    ]
