# Generated by Django 4.1.7 on 2023-03-29 06:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_data', '0003_vehicle_bookings_log_amount_payable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_bookings_log',
            name='booked_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
